name: Actualizar estado del issue

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  actualizar_estado_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Actualizar estado del issue
        if: github.event.issue.labels[0].name == 'En progreso'
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          STATE='{"state": "open"}'
          curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $TOKEN" -d "$STATE" "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
      - name: Actualizar estado del issue
        if: github.event.issue.labels[0].name == 'Cerrado' && contains(github.event.issue.labels.*.name, 'Aprobado')
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          STATE='{"state": "closed"}'
          curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $TOKEN" -d "$STATE" "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
      - name: Actualizar estado del issue
        if: github.event.issue.labels[0].name == 'Cerrado' && contains(github.event.issue.labels.*.name, 'Rechazado')
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          STATE='{"state": "closed"}'
          curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $TOKEN" -d "$STATE" "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
      - name: Actualizar estado del issue
        if: contains(github.event.issue.labels.*.name, 'En revisión')
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          STATE='{"state": "open"}'
          curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $TOKEN" -d "$STATE" "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
